### ISSUE TITLE
Samples can't find device unless it's on primary USB Bus

### ISSUE THREAD

**Issue by eheaton** [orbbec/astra#3] opened 2016-01-04 23:30 UTC
I have 2 USB 3.0 Busses connected to my macbook (one internal, one external) - while connected directly to the macbook, the samples boot up fine, but if it's connected external bus, I get the following error:

```
$ /path/to/AstraSDK-0.4.0-20151014T193346Z-osx-x64/build/bin/SimpleDepthViewer-SFML; exit;
2016-01-04 18:28:44,687 WARN  [context] Hold on to yer butts
2016-01-04 18:28:44,688 INFO  [context] configuration path: /path/to/AstraSDK-0.4.0-20151014T193346Z-osx-x64/lib/astra.toml
2016-01-04 18:28:44,688 INFO  [context] log file path: astra.log
2016-01-04 18:28:44,688 INFO  [context] plugin path: /path/to/AstraSDK-0.4.0-20151014T193346Z-osx-x64/lib/Plugins/
2016-01-04 18:28:44,695 INFO  [orbbec.ni.oni_adapter_plugin] Initializing OpenNI v2.3.0.15
2016-01-04 18:28:44,827 INFO  [orbbec.ni.oni_adapter_plugin] device connected: 2bc5/0403@0/8
2016-01-04 18:28:44,828 INFO  [astra.plugin_service] creating streamset: device/sensor0 28f163d0
2016-01-04 18:28:44,828 INFO  [orbbec.ni.device_streamset] opening device: 2bc5/0403@0/8
2016-01-04 18:28:44,831 WARN  [orbbec.ni.device_streamset] failed to open device:   Could not open "2bc5/0403@0/8": Failed to open the USB device!

2016-01-04 18:28:44,860 INFO  [orbbec.ni.oni_adapter_plugin] Initialized OpenNI v2.3.0.15
2016-01-04 18:28:44,877 INFO  [astra.plugins.xs.XSPlugin] Initializing XS plugin
2016-01-04 18:28:45,041 INFO  [context] client opening streamset: device/default
2016-01-04 18:28:45,041 INFO  [streamset_catalog] default uri provided.
2016-01-04 18:28:45,042 INFO  [astra.streamset] connecting to (7,0) on device/sensor0
2016-01-04 18:28:45,042 INFO  [astra.streamset] connecting to (1,0) on device/sensor0
Failed to load font "Inconsolata.otf" (failed to create the font face)
```

**Comment by JoshBlake** [comment] 2017-11-30 03:32
Can't reproduce on Windows or macOS Sierra 10.12.6. It's possible it was fixed in recent work that we will publish in January.

**Closed by JoshBlake** 2017-11-30 03:32 UTC

**Comment by Sciroccogti** [comment] 2021-01-24 07:25
I run into this issue too.
